name: Scrape Christies

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: christies-scrape
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ms-playwright-

      - name: Install Playwright (Chromium only)
        run: npx playwright install chromium

      - name: Run scraper
        env:
          AUCTION_URL: https://onlineonly.christies.com/s/handbags-online-new-york-edit/lots/3756?loadall=true
        run: npm run scrape

      - name: Move JSON into tracked folder
        run: |
          mkdir -p data
          mv out/data.json data/data.json

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/data.json
          git diff --cached --quiet || git commit -m "Update auction data"
          git push